#!/usr/bin/env tsx
/**
 * Generates docs/config/CONFIGURATION.md from the runtime config schema
 * (CONFIG_DEFINITIONS) and the per-environment override files. Run with
 * `npm run config:docs`. Pass --check to fail CI if the checked-in doc is
 * stale (drifted from the source of truth) instead of rewriting it.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONFIG_DEFINITIONS } from '../src/services/config/config-schema.js';
import { developmentOverrides } from '../src/config/environments/development.js';
import { stagingOverrides } from '../src/config/environments/staging.js';
import { productionOverrides } from '../src/config/environments/production.js';
import type { EnvironmentOverrides } from '../src/config/environments/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = join(__dirname, '..', '..', 'docs', 'config', 'CONFIGURATION.md');

const ENVIRONMENTS: Record<string, EnvironmentOverrides> = {
  development: developmentOverrides,
  staging: stagingOverrides,
  production: productionOverrides,
};

function render(): string {
  const lines: string[] = [];
  lines.push('<!-- AUTO-GENERATED by `npm run config:docs` in backend/. Do not edit by hand. -->');
  lines.push('# Configuration Reference');
  lines.push('');
  lines.push('## Runtime configuration keys');
  lines.push('');
  lines.push('| Key | Type | Description | Env var | Default | Sensitive |');
  lines.push('|-----|------|-------------|---------|---------|-----------|');
  for (const def of Object.values(CONFIG_DEFINITIONS)) {
    lines.push(
      `| \`${def.key}\` | ${def.type} | ${def.description} | ${def.envVar ? `\`${def.envVar}\`` : '—'} | \`${JSON.stringify(def.defaultValue)}\` | ${def.sensitive ? 'yes' : 'no'} |`,
    );
  }

  lines.push('');
  lines.push('## Environment overrides');
  lines.push('');
  const allKeys = Array.from(
    new Set(Object.values(ENVIRONMENTS).flatMap((overrides) => Object.keys(overrides))),
  ).sort();
  lines.push(`| Key | ${Object.keys(ENVIRONMENTS).join(' | ')} |`);
  lines.push(`|-----|${Object.keys(ENVIRONMENTS).map(() => '---').join('|')}|`);
  for (const key of allKeys) {
    const row = Object.values(ENVIRONMENTS).map((overrides) => (overrides as Record<string, unknown>)[key] ?? '—');
    lines.push(`| \`${key}\` | ${row.join(' | ')} |`);
  }
  lines.push('');
  lines.push('Secrets (API keys, DB credentials) are not stored in these files — see `infra/main.tf`');
  lines.push('for the AWS Secrets Manager resources referenced by `AWS_SECRETS_MANAGER_SECRET_ID`.');
  lines.push('');

  return lines.join('\n');
}

const content = render();
const checkOnly = process.argv.includes('--check');

if (checkOnly) {
  if (!existsSync(OUTPUT_PATH) || readFileSync(OUTPUT_PATH, 'utf-8') !== content) {
    console.error(`Config docs are stale. Run \`npm run config:docs\` and commit ${OUTPUT_PATH}.`);
    process.exit(1);
  }
  console.log('Config docs are up to date.');
} else {
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, content);
  console.log(`Wrote ${OUTPUT_PATH}`);
}
