'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

type ComplianceDashboardData = {
  overview: {
    totalChecks: number;
    passed: number;
    failed: number;
    warnings: number;
    overallScore: number;
    overallStatus: string;
    lastRunAt: string | null;
  };
  metrics: any;
  jurisdictionStatus: any[];
  recentAlerts: any[];
  regulatory: {
    metrics: any;
    recentUpdates: any[];
    upcomingDeadlines: any[];
  };
  automation: {
    recentRuns: any[];
    latestRun: any | null;
    taskHistory: any[];
  };
  generatedAt: string;
};

export default function ComplianceDashboardPage() {
  const [data, setData] = useState<ComplianceDashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [jurisdiction, setJurisdiction] = useState('GLOBAL');
  const [running, setRunning] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'checks' | 'regulatory' | 'alerts' | 'audit'>('overview');

  const fetchDashboard = async () => {
    setLoading(true);
    try {
      // In production, use real API client; here we simulate if API not available
      const res = await fetch(`/api/v1/compliance/automation/dashboard?jurisdiction=${jurisdiction}`).catch(() => null);
      if (res && res.ok) {
        const json = await res.json();
        setData(json.data);
      } else {
        // Fallback mock data for preview
        setData({
          overview: {
            totalChecks: 15,
            passed: 12,
            failed: 1,
            warnings: 2,
            overallScore: 88,
            overallStatus: 'review_required',
            lastRunAt: new Date().toISOString(),
          },
          metrics: {
            kycVerificationRate: 90,
            amlFlagRate: 1.2,
            highRiskTransactions: 312,
            sanctionsHits: 4,
            pepHits: 11,
            openAlerts: 3,
            criticalAlerts: 0,
            complianceScore: 88,
            gdprCompliance: 98.5,
          },
          jurisdictionStatus: [
            { jurisdiction: 'US', overallStatus: 'compliant', score: 92, kycComplianceRate: 90, amlFlagRate: 1.2, openAlerts: 1, criticalAlerts: 0, lastChecked: new Date().toISOString() },
            { jurisdiction: 'EU', overallStatus: 'review_required', score: 78, kycComplianceRate: 88, amlFlagRate: 1.5, openAlerts: 2, criticalAlerts: 0, lastChecked: new Date().toISOString() },
            { jurisdiction: 'UK', overallStatus: 'compliant', score: 90, kycComplianceRate: 87, amlFlagRate: 1.1, openAlerts: 0, criticalAlerts: 0, lastChecked: new Date().toISOString() },
          ],
          recentAlerts: [
            { id: 'alert_1', type: 'high_risk_ratio', severity: 'warning', status: 'open', message: 'WARNING: high_risk_ratio approaching threshold in US', jurisdiction: 'US', triggeredAt: new Date().toISOString(), autoGenerated: true },
            { id: 'alert_2', type: 'kyc_verification_rate', severity: 'info', status: 'open', message: 'KYC verification rate slightly below target in EU', jurisdiction: 'EU', triggeredAt: new Date().toISOString(), autoGenerated: true },
          ],
          regulatory: {
            metrics: { totalSources: 8, activeSources: 8, totalUpdates: 4, newUpdates: 2, criticalUpdates: 1, overdueReviews: 0, byJurisdiction: { US: 2, EU: 1, GLOBAL: 1 }, byCategory: { aml: 3, sanctions: 1 }, lastPollAt: new Date().toISOString() },
            recentUpdates: [
              { id: 'reg_1', jurisdiction: 'US', title: 'OFAC Adds 12 Entities to SDN List', impactLevel: 'critical', status: 'new', summary: '12 virtual currency addresses added', publishedAt: new Date().toISOString(), requiredActions: ['Screening', 'Freeze'] },
              { id: 'reg_2', jurisdiction: 'US', title: 'FinCEN Alert on Virtual Currency Mixing', impactLevel: 'high', status: 'new', summary: 'Enhanced due diligence for mixers', publishedAt: new Date().toISOString(), requiredActions: ['Update rules'] },
            ],
            upcomingDeadlines: [
              { id: 'reg_3', title: 'FATF Travel Rule Implementation', complianceDeadline: new Date(Date.now() + 60*24*3600*1000).toISOString(), jurisdiction: 'GLOBAL', impactLevel: 'high' },
            ],
          },
          automation: {
            recentRuns: [
              { runId: 'run_1', totalChecks: 15, passed: 12, failed: 1, warnings: 2, overallScore: 88, overallStatus: 'review_required', completedAt: new Date().toISOString(), jurisdiction: 'GLOBAL', durationMs: 1234 },
            ],
            latestRun: { runId: 'run_1', totalChecks: 15, passed: 12, failed: 1, warnings: 2, overallScore: 88, overallStatus: 'review_required', completedAt: new Date().toISOString(), jurisdiction: 'GLOBAL', results: [] },
            taskHistory: [
              { id: 'auto_1', type: 'checks', status: 'completed', jurisdiction: 'GLOBAL', triggeredBy: 'scheduler', startedAt: new Date(Date.now()-3600*1000).toISOString(), durationMs: 1200 },
              { id: 'auto_2', type: 'regulatory_poll', status: 'completed', triggeredBy: 'scheduler', startedAt: new Date(Date.now()-7200*1000).toISOString(), durationMs: 800 },
            ],
          },
          generatedAt: new Date().toISOString(),
        });
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboard();
    const interval = setInterval(fetchDashboard, 60_000);
    return () => clearInterval(interval);
  }, [jurisdiction]);

  const runAutomation = async () => {
    setRunning(true);
    try {
      await fetch('/api/v1/compliance/automation/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jurisdiction }),
      });
      await fetchDashboard();
    } catch (e) {
      console.error(e);
    } finally {
      setRunning(false);
    }
  };

  const runChecks = async () => {
    setRunning(true);
    try {
      await fetch('/api/v1/compliance/checks/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jurisdiction }),
      });
      await fetchDashboard();
    } catch (e) {
      console.error(e);
    } finally {
      setRunning(false);
    }
  };

  if (loading) {
    return (
      <div className="space-y-6 p-6">
        <h1 className="text-3xl font-bold">Compliance Dashboard</h1>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[1,2,3].map(i => <div key={i} className="h-32 bg-gray-100 rounded animate-pulse" />)}
        </div>
      </div>
    );
  }

  const scoreColor = data && data.overview.overallScore >= 80 ? 'text-green-600' : data && data.overview.overallScore >= 50 ? 'text-yellow-600' : 'text-red-600';
  const statusBadge = (status: string) => {
    const colors: any = {
      compliant: 'bg-green-100 text-green-800',
      review_required: 'bg-yellow-100 text-yellow-800',
      non_compliant: 'bg-red-100 text-red-800',
      open: 'bg-red-100 text-red-800',
      acknowledged: 'bg-yellow-100 text-yellow-800',
      resolved: 'bg-green-100 text-green-800',
      new: 'bg-blue-100 text-blue-800',
    };
    return <span className={`px-2 py-1 rounded text-xs font-medium ${colors[status] || 'bg-gray-100 text-gray-800'}`}>{status}</span>;
  };

  return (
    <div className="space-y-6 p-6 max-w-7xl mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold">Compliance Dashboard</h1>
          <p className="text-gray-600">Automated compliance monitoring — KYC, AML, Sanctions, GDPR, Regulatory Updates</p>
        </div>
        <div className="flex gap-2">
          <select value={jurisdiction} onChange={(e) => setJurisdiction(e.target.value)} className="border rounded px-3 py-2 text-sm">
            <option value="GLOBAL">GLOBAL</option>
            <option value="US">US</option>
            <option value="EU">EU</option>
            <option value="UK">UK</option>
            <option value="SG">SG</option>
            <option value="AU">AU</option>
          </select>
          <button onClick={runChecks} disabled={running} className="px-3 py-2 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:opacity-50">
            {running ? 'Running...' : 'Run Checks'}
          </button>
          <button onClick={runAutomation} disabled={running} className="px-3 py-2 bg-green-600 text-white rounded text-sm hover:bg-green-700 disabled:opacity-50">
            {running ? 'Running...' : 'Full Cycle'}
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b overflow-x-auto">
        {[
          { id: 'overview', label: 'Overview' },
          { id: 'checks', label: 'Checks' },
          { id: 'regulatory', label: 'Regulatory' },
          { id: 'alerts', label: 'Alerts' },
          { id: 'audit', label: 'Automation' },
        ].map((t) => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id as any)}
            className={`pb-2 px-3 border-b-2 text-sm font-medium whitespace-nowrap ${activeTab === t.id ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'}`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {activeTab === 'overview' && data && (
        <>
          {/* Score & Summary */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-gray-500">Compliance Score</CardTitle>
              </CardHeader>
              <CardContent>
                <div className={`text-3xl font-bold ${scoreColor}`}>{data.overview.overallScore}%</div>
                <div className="mt-1">{statusBadge(data.overview.overallStatus)}</div>
                <p className="text-xs text-gray-500 mt-2">Last run: {data.overview.lastRunAt ? new Date(data.overview.lastRunAt).toLocaleString() : 'Never'}</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-gray-500">Checks</CardTitle></CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.overview.passed}/{data.overview.totalChecks} passed</div>
                <div className="flex gap-2 mt-2 text-xs">
                  <span className="text-green-600">{data.overview.passed} pass</span>
                  <span className="text-yellow-600">{data.overview.warnings} warn</span>
                  <span className="text-red-600">{data.overview.failed} fail</span>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-gray-500">Regulatory</CardTitle></CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.regulatory.metrics.newUpdates} new</div>
                <div className="text-xs text-gray-600 mt-1">{data.regulatory.metrics.totalUpdates} total • {data.regulatory.metrics.criticalUpdates} critical</div>
                <div className="text-xs text-gray-500">{data.regulatory.metrics.activeSources} sources active</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-gray-500">Alerts & Metrics</CardTitle></CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.metrics.openAlerts} open</div>
                <div className="text-xs text-red-600">{data.metrics.criticalAlerts} critical</div>
                <div className="text-xs text-gray-600 mt-1">KYC {data.metrics.kycVerificationRate}% • AML {data.metrics.amlFlagRate}%</div>
              </CardContent>
            </Card>
          </div>

          {/* Jurisdictions */}
          <Card>
            <CardHeader>
              <CardTitle>Jurisdiction Status</CardTitle>
              <CardDescription>Per-jurisdiction compliance health</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead><tr className="text-left text-gray-500 border-b"><th className="py-2">Jurisdiction</th><th>Status</th><th>Score</th><th>KYC</th><th>AML</th><th>Open</th><th>Critical</th><th>Last Checked</th></tr></thead>
                  <tbody>
                    {data.jurisdictionStatus.map((j: any) => (
                      <tr key={j.jurisdiction} className="border-b">
                        <td className="py-2 font-medium">{j.jurisdiction}</td>
                        <td>{statusBadge(j.overallStatus)}</td>
                        <td>{j.score ?? '--'}%</td>
                        <td>{j.kycComplianceRate}%</td>
                        <td>{j.amlFlagRate}%</td>
                        <td>{j.openAlerts ?? 0}</td>
                        <td>{j.criticalAlerts ?? 0}</td>
                        <td className="text-xs text-gray-500">{new Date(j.lastChecked).toLocaleTimeString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <Card>
              <CardHeader><CardTitle>Recent Alerts</CardTitle></CardHeader>
              <CardContent>
                <div className="space-y-3 max-h-80 overflow-y-auto">
                  {data.recentAlerts.length === 0 && <p className="text-sm text-gray-500">No open alerts</p>}
                  {data.recentAlerts.map((a: any) => (
                    <div key={a.id} className="p-3 border rounded text-sm">
                      <div className="flex justify-between items-start gap-2">
                        <div className="font-medium truncate">{a.message}</div>
                        {statusBadge(a.severity)}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">{a.jurisdiction} • {new Date(a.triggeredAt).toLocaleString()} • {a.type}</div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader><CardTitle>Regulatory Updates</CardTitle></CardHeader>
              <CardContent>
                <div className="space-y-3 max-h-80 overflow-y-auto">
                  {data.regulatory.recentUpdates.map((u: any) => (
                    <div key={u.id} className="p-3 border rounded text-sm">
                      <div className="flex justify-between gap-2">
                        <div className="font-medium">{u.title}</div>
                        <span className={`text-xs px-1.5 py-0.5 rounded ${u.impactLevel === 'critical' ? 'bg-red-100 text-red-700' : u.impactLevel === 'high' ? 'bg-orange-100 text-orange-700' : 'bg-gray-100'}`}>{u.impactLevel}</span>
                      </div>
                      <div className="text-xs text-gray-600 mt-1 line-clamp-2">{u.summary}</div>
                      <div className="text-xs text-gray-500 mt-1">{u.jurisdiction} • {new Date(u.publishedAt).toLocaleDateString()} • {statusBadge(u.status)}</div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </>
      )}

      {activeTab === 'checks' && data && (
        <div className="grid grid-cols-1 gap-4">
          <Card>
            <CardHeader><CardTitle>Automated Checks History</CardTitle></CardHeader>
            <CardContent>
              <div className="space-y-2 max-h-[600px] overflow-y-auto">
                {data.automation.recentRuns.map((run: any) => (
                  <div key={run.runId} className="p-3 border rounded flex justify-between items-center text-sm">
                    <div>
                      <div className="font-medium">{run.runId} • {run.jurisdiction}</div>
                      <div className="text-xs text-gray-500">{new Date(run.completedAt).toLocaleString()} • {run.durationMs}ms • {run.totalChecks} checks</div>
                    </div>
                    <div className="text-right">
                      <div className={`font-bold ${run.overallScore >=80 ? 'text-green-600' : run.overallScore>=50 ? 'text-yellow-600' : 'text-red-600'}`}>{run.overallScore}%</div>
                      <div className="text-xs">{statusBadge(run.overallStatus)}</div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
          {data.automation.latestRun && (
            <Card>
              <CardHeader><CardTitle>Latest Run Details</CardTitle><CardDescription>{data.automation.latestRun.runId}</CardDescription></CardHeader>
              <CardContent>
                <div className="text-sm space-y-2">
                  <div>Score: {data.automation.latestRun.overallScore}% — {statusBadge(data.automation.latestRun.overallStatus)}</div>
                  <div>Passed: {data.automation.latestRun.passed} / Failed: {data.automation.latestRun.failed} / Warnings: {data.automation.latestRun.warnings}</div>
                  <div className="text-xs text-gray-500">Completed: {new Date(data.automation.latestRun.completedAt).toLocaleString()} • Duration: {data.automation.latestRun.durationMs}ms</div>
                  {data.automation.latestRun.results && data.automation.latestRun.results.length > 0 && (
                    <div className="mt-4">
                      <div className="font-medium mb-2">Check Results</div>
                      <div className="max-h-80 overflow-y-auto space-y-1">
                        {data.automation.latestRun.results.map((r: any) => (
                          <div key={r.id} className="flex justify-between text-xs border-b py-1">
                            <span>{r.name} ({r.category})</span>
                            <span className={`${r.status==='pass'?'text-green-600':r.status==='fail'?'text-red-600':'text-yellow-600'}`}>{r.status} {r.score ? `(${r.score}%)` : ''}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {activeTab === 'regulatory' && data && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <Card className="lg:col-span-2">
            <CardHeader><CardTitle>Regulatory Updates Feed</CardTitle><CardDescription>{data.regulatory.metrics.totalSources} sources • last poll {new Date(data.regulatory.metrics.lastPollAt).toLocaleString()}</CardDescription></CardHeader>
            <CardContent>
              <div className="space-y-3 max-h-[600px] overflow-y-auto">
                {data.regulatory.recentUpdates.map((u: any) => (
                  <div key={u.id} className="p-4 border rounded">
                    <div className="flex justify-between gap-2">
                      <h4 className="font-medium text-sm">{u.title}</h4>
                      {statusBadge(u.impactLevel)}
                    </div>
                    <p className="text-xs text-gray-600 mt-1">{u.summary}</p>
                    <div className="text-xs text-gray-500 mt-2">Jurisdiction: {u.jurisdiction} • Categories: {u.categories?.join(', ') || u.requiredActions?.slice(0,2).join(', ')}</div>
                    <div className="text-xs mt-1">Required Actions: {u.requiredActions?.slice(0,3).join(' • ')}</div>
                    <div className="flex gap-2 mt-2 text-xs">
                      {statusBadge(u.status)}
                      <span className="text-gray-500">{new Date(u.publishedAt).toLocaleDateString()}</span>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
          <div className="space-y-4">
            <Card>
              <CardHeader><CardTitle>Upcoming Deadlines</CardTitle></CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {data.regulatory.upcomingDeadlines.length === 0 && <p className="text-xs text-gray-500">No deadlines in next 60 days</p>}
                  {data.regulatory.upcomingDeadlines.map((d: any) => (
                    <div key={d.id} className="text-xs p-2 border rounded">
                      <div className="font-medium">{d.title}</div>
                      <div className="text-gray-500">Due: {d.complianceDeadline ? new Date(d.complianceDeadline).toLocaleDateString() : 'TBD'} • {d.jurisdiction}</div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader><CardTitle>By Jurisdiction</CardTitle></CardHeader>
              <CardContent>
                <div className="space-y-1 text-xs">
                  {Object.entries(data.regulatory.metrics.byJurisdiction).map(([juris, count]) => (
                    <div key={juris} className="flex justify-between"><span>{juris}</span><span>{String(count)}</span></div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      )}

      {activeTab === 'alerts' && data && (
        <Card>
          <CardHeader><CardTitle>Compliance Alerts</CardTitle><CardDescription>{data.recentAlerts.length} open alerts</CardDescription></CardHeader>
          <CardContent>
            <div className="space-y-2">
              {data.recentAlerts.map((a: any) => (
                <div key={a.id} className="p-3 border rounded text-sm flex justify-between gap-3">
                  <div>
                    <div className="font-medium">{a.message}</div>
                    <div className="text-xs text-gray-500">{a.id} • {a.jurisdiction} • {a.type} • {new Date(a.triggeredAt).toLocaleString()}</div>
                    <div className="text-xs mt-1 text-gray-600">Details: {JSON.stringify(a.details).slice(0,200)}</div>
                  </div>
                  <div className="flex flex-col gap-1 items-end">
                    {statusBadge(a.severity)}
                    {statusBadge(a.status)}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {activeTab === 'audit' && data && (
        <div className="grid grid-cols-1 gap-4">
          <Card>
            <CardHeader><CardTitle>Automation Task History</CardTitle><CardDescription>Recent automated compliance tasks</CardDescription></CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead><tr className="text-left text-gray-500 border-b"><th className="py-2">Task ID</th><th>Type</th><th>Status</th><th>Jurisdiction</th><th>Trigger</th><th>Started</th><th>Duration</th></tr></thead>
                  <tbody>
                    {data.automation.taskHistory.map((t: any) => (
                      <tr key={t.id} className="border-b">
                        <td className="py-2 font-mono truncate max-w-[120px]">{t.id}</td>
                        <td>{t.type}</td>
                        <td>{statusBadge(t.status)}</td>
                        <td>{t.jurisdiction || '-'}</td>
                        <td>{t.triggeredBy}</td>
                        <td>{new Date(t.startedAt).toLocaleString()}</td>
                        <td>{t.durationMs ? `${t.durationMs}ms` : '-'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      <div className="text-xs text-gray-400">
        Generated at {new Date(data?.generatedAt || Date.now()).toLocaleString()} • Automated compliance system v1.0 • Docs: /backend/docs/COMPLIANCE_GUIDE.md
      </div>
    </div>
  );
}
